# Generated by Django 4.2.1 on 2023-05-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_category_product_delete_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=1, upload_to='web_shop/products/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
