# Generated by Django 4.2.3 on 2023-07-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0013_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='product',
        ),
    ]
