# Generated by Django 4.2.3 on 2023-08-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0015_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='stuff.color'),
        ),
    ]
