# Generated by Django 4.2.3 on 2023-08-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0017_product_more_info_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.IntegerField(default=0),
        ),
    ]
