# Generated by Django 4.2.3 on 2023-08-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0018_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
