# Generated by Django 4.2.3 on 2023-09-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0019_product_alt_productimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='en',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
