# Generated by Django 4.2.3 on 2023-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0021_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_for_landing',
            field=models.BooleanField(default=False),
        ),
    ]
