# Generated by Django 4.2.3 on 2023-09-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0022_category_is_for_landing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_for_landing',
        ),
    ]
