# Generated by Django 4.2.3 on 2023-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0023_remove_category_is_for_landing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='web_shop/products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='web_shop/products/%Y/%m/'),
        ),
    ]
