# Generated by Django 4.2.3 on 2023-10-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0027_product_dirham_price_product_dirham_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='En',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
