# Generated by Django 4.2.3 on 2023-10-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0030_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordered',
            field=models.IntegerField(default=0),
        ),
    ]
