# Generated by Django 4.2.3 on 2023-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0031_product_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='media/logos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/products/%Y/%m/'),
        ),
    ]
