# Generated by Django 4.2.3 on 2024-02-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0033_product_price_bus_product_price_incity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_bus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_incity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_post',
        ),
    ]
