# Generated by Django 4.2.3 on 2024-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0034_remove_product_price_bus_remove_product_price_incity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='transit_price',
            field=models.IntegerField(blank=True, default=100000, null=True),
        ),
    ]
