# Generated by Django 4.2.3 on 2024-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0035_alter_product_transit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dirham_price',
            field=models.IntegerField(blank=True, default=17000, null=True),
        ),
    ]
