# Generated by Django 4.2.1 on 2023-05-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_alter_product_discount'),
        ('accounts', '0004_remove_user_wishlist_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(null=True, to='stuff.product'),
        ),
    ]
