# Generated by Django 4.2.3 on 2023-07-19 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_alter_product_discount'),
        ('accounts', '0006_alter_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='stuff.product'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('Product', models.ManyToManyField(related_name='comments', to='stuff.product')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.comment')),
                ('user', models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
