# Generated by Django 4.2.3 on 2023-07-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
