# Generated by Django 4.2.3 on 2023-07-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='currnent',
            field=models.BooleanField(default=False),
        ),
    ]
