# Generated by Django 4.2.3 on 2023-07-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_address_currnent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='currnent',
            new_name='current',
        ),
    ]
