# Generated by Django 4.2.3 on 2023-08-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_can_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
