# Generated by Django 4.2.3 on 2023-08-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0019_product_alt_productimage_alt'),
        ('accounts', '0021_comment_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='informing',
            field=models.ManyToManyField(blank=True, related_name='informing', to='stuff.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='stuff.product'),
        ),
    ]
