# Generated by Django 4.2.3 on 2023-09-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_comment_product_postcomment_productcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.comment')),
            ],
            bases=('accounts.comment',),
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='articleal_code',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
