# Generated by Django 4.2.3 on 2023-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_articleal_code_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(upload_to='web_shop/users/%Y/%m/'),
        ),
    ]
