# Generated by Django 4.2.3 on 2023-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(upload_to='media/users/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_send_way',
            field=models.CharField(choices=[('c', 'درون شهری'), ('b', 'اتوبوس'), ('p', 'پست معمولی'), ('t', 'تیپاکس (پس کرایه)')], default='t', max_length=1),
        ),
    ]
