# Generated by Django 4.2.3 on 2024-03-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_profileuser_image_alter_user_last_send_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link_dargah',
            field=models.CharField(default='False', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='redirect',
            field=models.BooleanField(default=False),
        ),
    ]
