# Generated by Django 4.2.3 on 2024-03-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_rename_link_dargah_user_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
