# Generated by Django 4.2.3 on 2024-06-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_user_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_code',
            field=models.BooleanField(default=False),
        ),
    ]
