# Generated by Django 4.2.3 on 2023-09-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='web_shop/publicitar/%Y/%m/%d/')),
                ('main_link', models.CharField(max_length=200)),
                ('out_link', models.CharField(max_length=200)),
            ],
        ),
    ]
