# Generated by Django 4.2.3 on 2023-09-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_publicitar_arg'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_for_landing',
            field=models.BooleanField(default=False),
        ),
    ]
