# Generated by Django 4.2.3 on 2023-09-18 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_articlecomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_post_is_for_landing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تیتر')),
                ('text', models.TextField(verbose_name='متن')),
                ('Cover', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر')),
                ('drafted', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پیش نویس')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='آدرس')),
                ('status', models.CharField(choices=[('p', 'انتشار یافته'), ('d', 'پیش نویس'), ('i', 'در انتظار انتشار'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('is_for_landing', models.BooleanField(default=False)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('Category', models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='دسته بندی')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
