# Generated by Django 4.2.3 on 2023-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_cover_alter_category_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to="'web_shop/blog/articles/%Y/%m/%d/'", verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to='web_shop/blog/categories/%Y/%m/%d/', verbose_name='تصویر'),
        ),
    ]
