# Generated by Django 4.2.3 on 2023-10-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_cover_alter_category_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to='web_shop/blog/articles/%Y/%m/', verbose_name='تصویر'),
        ),
    ]
