# Generated by Django 4.2.3 on 2023-10-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reference_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reference_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
