# Generated by Django 4.2.3 on 2023-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_reference_link_article_reference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/articles/%Y/%m/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/categories/%Y/%m/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='publicitar',
            name='image',
            field=models.ImageField(upload_to='media/publicitar/%Y/%m/'),
        ),
    ]
