# Generated by Django 4.2.3 on 2023-10-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='web_shop/excels/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
