# Generated by Django 4.2.3 on 2023-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administratorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelstuff',
            name='file',
            field=models.FileField(upload_to='media/excels/'),
        ),
    ]
