# Generated by Django 4.2.3 on 2023-08-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='packing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
