# Generated by Django 4.2.3 on 2023-09-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
