# Generated by Django 4.2.3 on 2023-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_bool',
            field=models.BooleanField(default=False),
        ),
    ]
