# Generated by Django 4.2.3 on 2023-10-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
