# Generated by Django 4.2.3 on 2024-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_interception_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='not_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
