# Generated by Django 4.2.3 on 2023-07-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0002_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigTitle', models.CharField(max_length=100)),
                ('titleId', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
    ]
