# Generated by Django 4.2.3 on 2023-07-31 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigTitle', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='bigTitle',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='titleId',
        ),
        migrations.AddField(
            model_name='faq',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facades.faqgroup'),
            preserve_default=False,
        ),
    ]
