# Generated by Django 4.2.3 on 2023-07-31 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0004_faqgroup_remove_faq_bigtitle_remove_faq_titleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='facades.faqgroup'),
        ),
    ]
