# Generated by Django 4.2.3 on 2023-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0005_alter_faq_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='web_shop/Covers/%Y/%m/%d/')),
                ('button', models.CharField(max_length=200)),
                ('main_link', models.CharField(max_length=200)),
                ('out_link', models.CharField(max_length=200)),
            ],
        ),
    ]
