# Generated by Django 4.2.3 on 2023-08-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0006_endbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='endbanner',
            name='arg',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
