# Generated by Django 4.2.3 on 2023-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0007_endbanner_arg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endbanner',
            name='arg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
