# Generated by Django 4.2.3 on 2023-08-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0008_alter_endbanner_arg'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
