# Generated by Django 4.2.3 on 2023-08-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0009_shops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shops',
            new_name='shop',
        ),
    ]
