# Generated by Django 4.2.3 on 2023-08-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0010_rename_shops_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default=1, upload_to='web_shop/banners/'),
            preserve_default=False,
        ),
    ]
