# Generated by Django 4.2.3 on 2023-09-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0011_shop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigTitle', models.CharField(max_length=200)),
                ('smallTitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='web_shop/banners/%Y/%m/%d/')),
                ('for_what', models.CharField(choices=[('2', '2col')], max_length=1)),
            ],
        ),
    ]
