# Generated by Django 4.2.3 on 2023-09-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0014_alter_banner_for_what'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='arg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='main_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='out_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
