# Generated by Django 4.2.3 on 2023-09-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0016_delete_cover_alter_banner_for_what'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EndBanner',
        ),
        migrations.AddField(
            model_name='banner',
            name='button',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='for_what',
            field=models.CharField(choices=[('c2', '2col'), ('c3', '3col'), ('f1', 'fisrt1'), ('f2', 'fisrt2'), ('b1', 'big1'), ('e1', 'end1')], max_length=2),
        ),
    ]
