# Generated by Django 4.2.3 on 2023-10-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0020_alter_banner_for_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='web_shop/banners/%Y/%m/'),
        ),
    ]
