# Generated by Django 4.2.3 on 2023-10-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0022_alter_survey_phonenumber_alter_survey_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('ename', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='web_shop/config/logo/')),
            ],
        ),
    ]
