# Generated by Django 4.2.3 on 2023-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0023_configshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshop',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
