# Generated by Django 4.2.3 on 2023-10-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0025_configshop_aboutus_configshop_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshop',
            name='black_logo',
            field=models.ImageField(default=1, upload_to='web_shop/config/logo/'),
            preserve_default=False,
        ),
    ]
