# Generated by Django 4.2.3 on 2023-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0026_configshop_black_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshop',
            name='color',
            field=models.CharField(default='82981a', max_length=6),
        ),
    ]
