# Generated by Django 4.2.3 on 2023-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0028_alter_banner_for_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='for_what',
            field=models.CharField(choices=[('c2', '2col'), ('c3', '3col'), ('f1', 'fisrt1'), ('f2', 'fisrt2'), ('b1', 'big1'), ('e1', 'end1'), ('t1', 'category1'), ('t2', 'category2'), ('t3', 'category3'), ('ct', 'category page'), ('ds', 'dashboard'), ('ne', 'news'), ('au', 'aboutUs'), ('ay', 'aboutUsBanner'), ('co', 'contact'), ('fq', 'FAQ'), ('ff', 'full width FAQ'), ('to', 'Track Order')], max_length=2),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='media/banners/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='configshop',
            name='black_logo',
            field=models.ImageField(upload_to='media/config/logo/'),
        ),
        migrations.AlterField(
            model_name='configshop',
            name='logo',
            field=models.ImageField(upload_to='media/config/logo/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='media/banners/'),
        ),
    ]
