# Generated by Django 4.2.3 on 2023-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0029_alter_banner_for_what_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshop',
            name='home_page',
            field=models.CharField(choices=[('a1', 'gizmo'), ('a2', 'vahdat')], default='a1', max_length=2),
        ),
    ]
