# Generated by Django 4.2.3 on 2023-11-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0030_configshop_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configshop',
            name='home_page',
            field=models.CharField(choices=[('a1', 'discounted_showcase'), ('a2', 'category_showcase')], default='a1', max_length=2),
        ),
    ]
