# Generated by Django 4.2.3 on 2023-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0033_rule_alter_banner_for_what'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshop',
            name='e_namad',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
