# Generated by Django 4.2.3 on 2024-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0035_banner_abs_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshop',
            name='active_dargah',
            field=models.BooleanField(default=True),
        ),
    ]
