# Generated by Django 4.2.3 on 2024-09-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facades', '0036_configshop_active_dargah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configshop',
            name='color',
            field=models.CharField(default='#82981a', max_length=7),
        ),
    ]
